//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bus_Application
{
    using System;
    using System.Collections.Generic;
    
    public partial class BUS
    {
        public BUS()
        {
            this.ROUTEs = new HashSet<ROUTE>();
            this.STATION_BUSES = new HashSet<STATION_BUSES>();
        }
    
        public int Bus_ID { get; set; }
        public string Bus_Description { get; set; }
        public string Bus_Provider { get; set; }
        public string Bus_Color { get; set; }
    
        public virtual ICollection<ROUTE> ROUTEs { get; set; }
        public virtual ICollection<STATION_BUSES> STATION_BUSES { get; set; }
    }
}
