//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bus_Application
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Teste_OnibusContext : DbContext
    {
        public Teste_OnibusContext()
            : base("name=Teste_OnibusContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LANDMARK_KNOWN_AS> LANDMARK_KNOWN_AS { get; set; }
        public virtual DbSet<STATION_BUSES> STATION_BUSES { get; set; }
        public virtual DbSet<ROUTE> ROUTEs { get; set; }
        public virtual DbSet<BUS> BUS { get; set; }
        public virtual DbSet<STATION> STATIONS { get; set; }
        public virtual DbSet<LANDMARK> LANDMARKs { get; set; }
    }
}
