//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bus_Application
{
    using System;
    using System.Collections.Generic;
    
    public partial class LANDMARK
    {
        public LANDMARK()
        {
            this.LANDMARK_KNOWN_AS = new HashSet<LANDMARK_KNOWN_AS>();
        }
    
        public int Landmark_ID { get; set; }
        public System.Data.Entity.Spatial.DbGeography Landmark_Coordinates { get; set; }
    
        public virtual ICollection<LANDMARK_KNOWN_AS> LANDMARK_KNOWN_AS { get; set; }
    }
}
