//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bus_Application
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROUTE
    {
        public int Route_ID { get; set; }
        public Nullable<int> Bus_ID { get; set; }
        public System.Data.Entity.Spatial.DbGeography Route_Coordinates { get; set; }
    
        public virtual BUS BUS { get; set; }
    }
}
