//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bus_Application
{
    using System;
    using System.Collections.Generic;
    
    public partial class STATION
    {
        public STATION()
        {
            this.STATION_BUSES = new HashSet<STATION_BUSES>();
        }
    
        public int Station_ID { get; set; }
        public string Station_Description { get; set; }
        public System.Data.Entity.Spatial.DbGeography Station_Coordinates { get; set; }
    
        public virtual ICollection<STATION_BUSES> STATION_BUSES { get; set; }
    }
}
