//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bus_Application
{
    using System;
    using System.Collections.Generic;
    
    public partial class STATION_BUSES
    {
        public int Station_Buses_ID { get; set; }
        public int Buses_FK { get; set; }
        public int Stations_Fk { get; set; }
    
        public virtual BUS BUS { get; set; }
        public virtual STATION STATION { get; set; }
    }
}
